name: PROD Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ssh-key: "${{ secrets.PROD_SSH_KEY }}"
  host: "${{ vars.PROD_NAME }}@${{ vars.PROD_IP }}"
  name: "${GITHUB_REPOSITORY#*/}-prod"

jobs:
  Build:
    runs-on: ubuntu-22.04
    env:
      tag: "latest" #or ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build . -t ${{ env.name }}:${{ env.tag }}

      - name: Save docker image
        run: |
          docker save -o ${{ env.name }}.tar ${{ env.name }}:${{ env.tag }}

      - name: Generate SSH key
        run: |
          echo "${{ env.ssh-key }}" > ssh-key.pem
          sudo chmod 400 ssh-key.pem

      - name: Copy image to EC2
        run: |
          scp -i ssh-key.pem -o StrictHostKeyChecking=no ${{ env.name }}.tar ${{ env.host }}:${{ env.name }}.tar

  Deploy:
    needs: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Generate SSH key
        run: |
          echo "${{ env.ssh-key }}" > ssh-key.pem
          sudo chmod 400 ssh-key.pem

      - name: Start image
        run: |
          ssh -i ssh-key.pem -o StrictHostKeyChecking=no ${{ env.host }} ' \
          sudo docker load -i '${{ env.name }}'.tar && \
          sudo docker compose -f backend/compose.yaml up -d && \
          sudo docker image prune -af'